name: 02 Steps Types Action

on:
    workflow_dispatch:

jobs:
    say-hello-in-line-bash:
        runs-on: ubuntu-24.04
        steps:
            - run: echo "Hello people!!"

    say-pwd-in-line-bash:
        runs-on: ubuntu-24.04
        steps:
            - run: echo $PWD

    say-hello-in-line-python:
        runs-on: ubuntu-24.04
        steps:
            - run: print("Hello People !!")
              shell: python

    say-hello-in-line-javascript:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/hello-world-javascript-action@v1.1
              with:
                who-to-greet: "people !!"
